
stages:
- test
- docker_build

test:
  image: "python:2"
  stage: test
  script:
  - make deps
  - make test
docker:
  image: docker:stable
  services:
  - docker:dind
  stage: docker_build
  script:
  -  apk add --update make
  -  docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
  -  docker build -t registry.gitlab.com/ola0605/se_hello_printer_app .
  -  docker push registry.gitlab.com/ola0605/se_hello_printer_app
  -  #make docker_build
